services:
  nestjs:
    build: ./Pitchcoach-BACK
    ports:
      - "3000:3000"
    env_file:
      - ./Pitchcoach-BACK/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/poki?schema=public
      AI_SERVER_URL: http://fastapi-ai:8000
    depends_on:
      - postgres
      - fastapi-ai
    restart: always

  fastapi-ai:
    build: ./Pitchcoach-AI
    ports:
      - "8000:8000"
    env_file:
      - ./Pitchcoach-AI/.env
    volumes:
      - ./Pitchcoach-AI/credentials:/app/credentials:ro
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poki
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
