name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/Pitchcoach-BACK
            git fetch origin main
            git checkout main
            git pull --ff-only origin main
            cd ~
            docker compose -f docker-compose.yml config -q
            docker compose -f docker-compose.yml up -d --build nestjs
